In [1]:
import os
import s3fs
os.environ["AWS_ACCESS_KEY_ID"] = 'GS9R64A13HEFSAH06HKP'
os.environ["AWS_SECRET_ACCESS_KEY"] = 'su7YaMXb7O0QLOabetOJe+hokn+kfrqlOfRG+Xap'
os.environ["AWS_SESSION_TOKEN"] = 'eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJHUzlSNjRBMTNIRUZTQUgwNkhLUCIsImFsbG93ZWQtb3JpZ2lucyI6WyIqIl0sImF1ZCI6WyJtaW5pby1kYXRhbm9kZSIsIm9ueXhpYSIsImFjY291bnQiXSwiYXV0aF90aW1lIjoxNzc5NzQ3OTQ3LCJhenAiOiJvbnl4aWEiLCJlbWFpbCI6ImFyc2VuZS1nYWJ5Lm1iYWJlaC1tZXllLmF1ZGl0ZXVyQGxlY25hbS5uZXQiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZXhwIjoxNzgwNjU5NDM2LCJmYW1pbHlfbmFtZSI6Ik1CQUJFSCBNRVlFIiwiZ2l2ZW5fbmFtZSI6IkFyc2VuZSIsImdyb3VwcyI6WyJVU0VSX09OWVhJQSJdLCJpYXQiOjE3ODAwNTQ2MzYsImlzcyI6Imh0dHBzOi8vYXV0aC5sYWIuc3NwY2xvdWQuZnIvYXV0aC9yZWFsbXMvc3NwY2xvdWQiLCJqdGkiOiJvbnJ0cnQ6NDhjNThiYjktNWMzOS05M2JhLWUwODctZjkxMmY4NTY3ZjRjIiwibG9jYWxlIjoiZnIiLCJuYW1lIjoiQXJzZW5lIE1CQUJFSCBNRVlFIiwicG9saWN5Ijoic3Rzb25seSIsInByZWZlcnJlZF91c2VybmFtZSI6ImRlbW9uIiwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iLCJkZWZhdWx0LXJvbGVzLXNzcGNsb3VkIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiIsImRlZmF1bHQtcm9sZXMtc3NwY2xvdWQiXSwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBncm91cHMgZW1haWwiLCJzaWQiOiJtLWdoQ19KWEZoTWd4ZXN5YWlQem56aDEiLCJzdWIiOiJlZWNjODk3OS04OTRhLTQ0MzYtYjg0MS05NzE5ZTA1MGZmYmYiLCJ0eXAiOiJCZWFyZXIifQ.CovyQBqB16cfVenAwy1J0LDEiZZIM6zp6fJAhLPhXM2F8kzSqiOYmOc-3Fb1h_Dj_bmhObaMHYsWcYLVk9ipKw'
os.environ["AWS_DEFAULT_REGION"] = 'us-east-1'
fs = s3fs.S3FileSystem(
    client_kwargs={'endpoint_url': 'https://'+'minio.lab.sspcloud.fr'},
    key = os.environ["AWS_ACCESS_KEY_ID"], 
    secret = os.environ["AWS_SECRET_ACCESS_KEY"], 
    token = os.environ["AWS_SESSION_TOKEN"])

In [2]:
fs.ls("demon/velib")

['demon/velib/.keep', 'demon/velib/data']

In [16]:
import pandas as pd
import numpy as np
import geopandas as gpd

In [18]:
import geopandas as gpd
import requests
from io import BytesIO

url = "https://minio.lab.sspcloud.fr/demon/velib/data/brute/velib-disponibilite-en-temps-reel.parquet"

response = requests.get(url)
response.raise_for_status()

with BytesIO(response.content) as buffer:
    gdf = gpd.read_parquet(buffer)

In [19]:
gdf

,stationcode,name,is_installed,capacity,numdocksavailable,numbikesavailable,mechanical,ebike,is_renting,is_returning,duedate,coordonnees_geo,nom_arrondissement_communes,code_insee_commune,station_opening_hours
0,16107,Benjamin Godard - Victor Hugo,OUI,35,33,2,2,0,OUI,OUI,2026-05-12 13:32:19+02:00,POINT (2.27572 48.86598),Paris,75056,None
1,32304,Charcot - Benfleet,OUI,28,26,1,0,1,OUI,OUI,2026-05-12 13:23:11+02:00,POINT (2.44052 48.87837),Romainville,93063,None
2,9020,Toudouze - Clauzel,OUI,21,17,3,1,2,OUI,OUI,2026-05-12 13:23:29+02:00,POINT (2.33736 48.8793),Paris,75056,None
3,14111,Cassini - Denfert-Rochereau,OUI,25,15,10,3,7,OUI,OUI,2026-05-12 13:31:31+02:00,POINT (2.33604 48.83753),Paris,75056,None
4,32017,Basilique,OUI,22,10,9,1,8,OUI,OUI,2026-05-12 13:30:33+02:00,POINT (2.35887 48.93627),Saint-Denis,93066,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1506,15204,Square Bela Bartok,OUI,24,2,22,16,6,OUI,OUI,2026-05-12 13:32:40+02:00,POINT (2.28444 48.85098),Paris,75056,None
1507,19018,Cité de la Musique,OUI,60,37,19,4,15,OUI,OUI,2026-05-12 13:32:36+02:00,POINT (2.39258 48.8888),Paris,75056,None
1508,9104,Caumartin - Provence,OUI,22,13,9,4,5,OUI,OUI,2026-05-12 13:31:15+02:00,POINT (2.32847 48.87442),Paris,75056,None
1509,12105,Bercy - Villot,OUI,33,13,17,14,3,OUI,OUI,2026-05-12 13:30:07+02:00,POINT (2.37679 48.8418),Paris,75056,None
1510,8203,Matignon - Faubourg Saint-Honoré,OUI,35,2,33,14,19,OUI,OUI,2026-05-12 13:32:24+02:00,POINT (2.3139 48.8715),Paris,75056,None

In [14]:
df_2 = gpd.read_parquet("https://minio.lab.sspcloud.fr/demon/velib/data/brute/velib-disponibilite-en-temps-reel.parquet")

ArrowInvalid: Unrecognized filesystem type in URI: https://minio.lab.sspcloud.fr/demon/velib/data/brute/velib-disponibilite-en-temps-reel.parquet

In [11]:
df_2

,stationcode,name,is_installed,capacity,numdocksavailable,numbikesavailable,mechanical,ebike,is_renting,is_returning,duedate,coordonnees_geo,nom_arrondissement_communes,code_insee_commune,station_opening_hours
0,16107,Benjamin Godard - Victor Hugo,OUI,35,33,2,2,0,OUI,OUI,2026-05-12 13:32:19+02:00,"b'\x01\x01\x00\x00\x00M\x84\rO\xaf4\x02@,\xf2\...",Paris,75056,None
1,32304,Charcot - Benfleet,OUI,28,26,1,0,1,OUI,OUI,2026-05-12 13:23:11+02:00,b'\x01\x01\x00\x00\x00\xfal\xcda1\x86\x03@\xb5...,Romainville,93063,None
2,9020,Toudouze - Clauzel,OUI,21,17,3,1,2,OUI,OUI,2026-05-12 13:23:29+02:00,b'\x01\x01\x00\x00\x00\x01\x00\x00\xd8\xe9\xb2...,Paris,75056,None
3,14111,Cassini - Denfert-Rochereau,OUI,25,15,10,3,7,OUI,OUI,2026-05-12 13:31:31+02:00,b'\x01\x01\x00\x00\x00\xca\xff\xffT3\xb0\x02@\...,Paris,75056,None
4,32017,Basilique,OUI,22,10,9,1,8,OUI,OUI,2026-05-12 13:30:33+02:00,b'\x01\x01\x00\x00\x00\xdd3\xb7~\xf5\xde\x02@\...,Saint-Denis,93066,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1506,15204,Square Bela Bartok,OUI,24,2,22,16,6,OUI,OUI,2026-05-12 13:32:40+02:00,b'\x01\x01\x00\x00\x00\x8b\x8f\xa3d\x86F\x02@w...,Paris,75056,None
1507,19018,Cité de la Musique,OUI,60,37,19,4,15,OUI,OUI,2026-05-12 13:32:36+02:00,b'\x01\x01\x00\x00\x00\x00H\xce\x9b\x01$\x03@]...,Paris,75056,None
1508,9104,Caumartin - Provence,OUI,22,13,9,4,5,OUI,OUI,2026-05-12 13:31:15+02:00,b'\x01\x01\x00\x00\x00\x00\x00\x00 \xb4\xa0\x0...,Paris,75056,None
1509,12105,Bercy - Villot,OUI,33,13,17,14,3,OUI,OUI,2026-05-12 13:30:07+02:00,b'\x01\x01\x00\x00\x00\x84\x02 \xdd\xa7\x03\x0...,Paris,75056,None
1510,8203,Matignon - Faubourg Saint-Honoré,OUI,35,2,33,14,19,OUI,OUI,2026-05-12 13:32:24+02:00,"b'\x01\x01\x00\x00\x00\xdc\'""\xff\xdb\x82\x02@...",Paris,75056,None

In [ ]:

# on appel notre fichier
fs.get("demon/velib/data/brute/velib-disponibilite-en-temps-reel.parquet", "velib-disponibilite-en-temps-reel.parquet")

# on le charge 
df = pd.read_parquet('velib-disponibilite-en-temps-reel.parquet')

#### Analyse exploratoire

In [6]:
# On regarde les 5 premières lignes pour verifier que le fichier est chargé  
display(df.head())

# On vérifie le nom exact des colonnes et les types
print(df.info())

# On regarde s'il y a des valeurs manquantes
print(df.isna().sum())

,stationcode,name,is_installed,capacity,numdocksavailable,numbikesavailable,mechanical,ebike,is_renting,is_returning,duedate,coordonnees_geo,nom_arrondissement_communes,code_insee_commune,station_opening_hours
0,16107,Benjamin Godard - Victor Hugo,OUI,35,33,2,2,0,OUI,OUI,2026-05-12 13:32:19+02:00,"b'\x01\x01\x00\x00\x00M\x84\rO\xaf4\x02@,\xf2\...",Paris,75056,None
1,32304,Charcot - Benfleet,OUI,28,26,1,0,1,OUI,OUI,2026-05-12 13:23:11+02:00,b'\x01\x01\x00\x00\x00\xfal\xcda1\x86\x03@\xb5...,Romainville,93063,None
2,9020,Toudouze - Clauzel,OUI,21,17,3,1,2,OUI,OUI,2026-05-12 13:23:29+02:00,b'\x01\x01\x00\x00\x00\x01\x00\x00\xd8\xe9\xb2...,Paris,75056,None
3,14111,Cassini - Denfert-Rochereau,OUI,25,15,10,3,7,OUI,OUI,2026-05-12 13:31:31+02:00,b'\x01\x01\x00\x00\x00\xca\xff\xffT3\xb0\x02@\...,Paris,75056,None
4,32017,Basilique,OUI,22,10,9,1,8,OUI,OUI,2026-05-12 13:30:33+02:00,b'\x01\x01\x00\x00\x00\xdd3\xb7~\xf5\xde\x02@\...,Saint-Denis,93066,None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1511 entries, 0 to 1510
Data columns (total 15 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   stationcode                  1511 non-null   object
 1   name                         1511 non-null   object
 2   is_installed                 1511 non-null   object
 3   capacity                     1511 non-null   int64
 4   numdocksavailable            1511 non-null   int64
 5   numbikesavailable            1511 non-null   int64
 6   mechanical                   1511 non-null   int64
 7   ebike                        1511 non-null   int64
 8   is_renting                   1511 non-null   object
 9   is_returning                 1511 non-null   object
 10  duedate                      1511 non-null   datetime64[ms, Europe/Berlin]
 11  coordonnees_geo              1511 non-null   object
 12  nom_arrondissement_communes  1511 non-null   object
 13  code_insee_commune           1511 non-null   object
 14  station_opening_hours        0 non-null      object
dtypes: datetime64[ms, Europe/Berlin](1), int64(5), object(9)
memory usage: 177.2+ KB
None
stationcode                       0
name                              0
is_installed                      0
capacity                          0
numdocksavailable                 0
numbikesavailable                 0
mechanical                        0
ebike                             0
is_renting                        0
is_returning                      0
duedate                           0
coordonnees_geo                   0
nom_arrondissement_communes       0
code_insee_commune                0
station_opening_hours          1511
dtype: int64

### Construction des indicateurs

In [12]:
# On fait le calcul 
df['occupation_rate'] = df['numbikesavailable'] / df['capacity']
df['occupation_rate'] = df['occupation_rate'] * 100


df['occupation_rate'] = df['occupation_rate'].replace(np.inf, 0)

# On affiche la moyenne
print("Taux d'occupation moyen :")
print(df['occupation_rate'].mean())

Taux d'occupation moyen :
37.77153082181253

In [18]:
# On calcule le total de chaque type de vélo (electrique et mécanique)
nb_total_electrique = df['ebike'].sum()
nb_total_mecanique = df['mechanical'].sum()
n = df['numbikesavailable'].sum() #avec n le nombre de vélos total

# On calcule le pourcentage de vélos électriques
# (Nombre électrique / n) * 100
part_electrique = (nb_total_electrique / n) * 100

# On calcul le pourcentage de vélos méca
# (nombre de velos mécanique / n) * 100
part_mecanique = (nb_total_mecanique / n) * 100

print(f"Total vélos électriques : {nb_total_electrique}")
print(f"Total vélos mécaniques : {nb_total_mecanique}")
print(f"La part de l'électrique est de : {part_electrique:.2f}% et la part de vélo mécanique est de : {part_mecanique:.2f}%")

Total vélos électriques : 7495
Total vélos mécaniques : 11328
La part de l'électrique est de : 39.82% et la part de vélo mécanique est de : 60.18%

### Analyse par commune

In [20]:
# ici je vais faire un groupby des données par le nom de la commune
# Et lui demandé la moyenne pour le nombre de vélos et le taux d'occupation
commune = df.groupby('nom_arrondissement_communes')[['numbikesavailable', 'occupation_rate']].mean()

# 
# je trie tableau pour avoir les communes avec le plus de vélos en premier
commune = commune.sort_values(by='numbikesavailable', ascending=False)

# top 10 premières des communes 
print("--- TOP 10 DES COMMUNES PAR DISPONIBILITÉ ---")
display(commune.head(10))

--- TOP 10 DES COMMUNES PAR DISPONIBILITÉ ---

                             numbikesavailable  occupation_rate
nom_arrondissement_communes
Nogent-sur-Marne                     25.750000        63.580145
Villeneuve-la-Garenne                24.666667        75.497076
Joinville-le-Pont                    22.000000        55.000000
Sceaux                               21.000000        68.552189
Issy-les-Moulineaux                  20.363636        56.405066
Créteil                              19.882353        71.859233
Noisy-le-Sec                         18.500000        63.571429
Puteaux                              18.333333        66.677019
Saint-Maurice                        18.000000        65.669516
Nanterre                             17.375000        59.576014